## spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
## spring.datasource.username=${DB_USER}
## spring.datasource.password=${DB_PASSWORD}
## spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## spring.jpa.hibernate.ddl-auto=update
## spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#spring.datasource.url=jdbc:mysql://nabadatabase.cliacqmekc7s.us-east-2.rds.amazonaws.com:3306/nabaDatabase
#spring.datasource.username=root
#spring.datasource.password=nabaTest76!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#mybatis-plus.sql-script.enable=false
#mybatis-plus.global-config.db-config.enable-sql-runner=false
#spring.main.allow-bean-definition-overriding=true






#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cosc?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 12345678
#
#
#  main:
#    allow-bean-definition-overriding: true
#
##mybatis-plus:
##      configuration:
##        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##
##
##
# volunteer database

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/volunteer?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none   # 👈 change this to 'none', 'update', 'validate', or 'create'
    show-sql: true     # optional: log SQL to console
    properties:
      hibernate:
        format_sql: true  # optional: prettify SQL output

  main:
    allow-bean-definition-overriding: true

##mybatis-plus:
##      configuration:
##        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
